### PR TITLE
🖥️ Auto-add attribute codefix

### PR DESCRIPTION
**Pull request by heytherewill**
Codefix for auto adding `[Watch]`, `[Messager]` or `[Filter]` attributes, depending on what your system needs. Good stuff.

@isadorasophia Would love your feedback on what the defaults should be for these. Right now I'm adding an empty attribute, but we can be clever and use the code fixes to educate and [nudge](https://en.wikipedia.org/wiki/Nudge_theory) people towards better decisions. Adding an empty attribute is fine, but adding a smart attribute is better (and not much more expensive since the heavy lifting is already done).

### CODE REVIEW

**Comment by isadorasophia** [comment]
Awesome, I'm curious on what we could have for smart attributes!! For the default values:
- `[Filter(ContextAccessorFilter.None)]` (since usually you are not using a filter if you are not using anything
- `Messager` and `Filter` are really tricky though... because they are basically useless without a type argument (we could also suggest removing the IMessager/IReactive inheritance)

**Comment by heytherewill** [comment]
@isadorasophia Implemented, please review

**Comment by isadorasophia** [comment]
Thanks @heytherewill! I'm thinking whether the [Messager] and [Watch] can be misleading here. Is the code fix right now just adding a [Messager]/[Watch] attribute?

Maybe we could add something like `[Messager(typeof())]` and the person can fill the gaps...? I'm not sure whether people can be misled into thinking that `[Messager]`/`[Watch]` attribute will work by themselves (which won't in a non-obvious way, they need to define the type)

**Comment by heytherewill** [comment]
Oh, that's not a bad idea! I wonder if we can control the caret to move it to inside the typepf, but adding broken syntax, in this case, is a good idea

**Comment by heytherewill** [comment]
@isadorasophia I ended up creating partial attributes for all possible fixes. For Filter I went with `AllOf` and they all have empty typof expressions for the user to fill in. I think it's way better this way. The moving caret part wasn't working, though, so I'll wait for .NET 8 to be stable to try again on an IDE that fully supports it 😂

**Review by isadorasophia — APPROVED** [review]
Sounds good! o/

**Pull request merged**
